import turtle
turtle.bgcolor("black")
turtle.title("Heart")
pen = turtle.Pen()

pen.pensize(3)
pen.begin_fill()
pen.fillcolor("red")
pen.lt(140)
pen.fd(170)
pen.circle(-70,180)
pen.setheading(60)
pen.circle(-70,180)
pen.fd(170)
pen.end_fill()
